import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Logo from "/public/assets/logo.png";
import { Inter, Roboto_Mono } from "next/font/google";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-m",
});

export const metadata: Metadata = {
  title: "넥스트앱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <header className="w-full h-[60px] bg-black flex justify-center">
          <Image height={40} width={150} src={Logo} alt="logo"></Image>
        </header>
        {children}
      </body>
    </html>
  );
}
